"""core_schema

Revision ID: 0759e6de55ba
Revises:
Create Date: 2026-04-10 16:23:10.744573+00:00

"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

import sqlalchemy as sa
from alembic import op

revision: str = "0759e6de55ba"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

def _odds_history_statements() -> list[str]:
    """Return individual SQL statements from odds_history.sql, stripping comments."""
    sql_path = Path(__file__).parent.parent.parent / "sql" / "odds_history.sql"
    text = sql_path.read_text()
    # Strip -- comments and split on semicolons
    lines = [
        line for line in text.splitlines() if not line.strip().startswith("--")
    ]
    statements = [s.strip() for s in "\n".join(lines).split(";") if s.strip()]
    return statements


def upgrade() -> None:
    # Extensions
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gin")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bookmakers",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("base_url", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmakers")),
        sa.UniqueConstraint("slug", name=op.f("uq_bookmakers_slug")),
    )
    op.create_table(
        "reference_sources",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_sources")),
        sa.UniqueConstraint("slug", name=op.f("uq_reference_sources_slug")),
    )
    op.create_table(
        "sports",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sports")),
        sa.UniqueConstraint("slug", name=op.f("uq_sports_slug")),
    )
    op.create_table(
        "competitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sport_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("abbreviation", sa.Text(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
            name=op.f("fk_competitions_sport_id_sports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_competitions")),
        sa.UniqueConstraint("sport_id", "slug", name=op.f("uq_competitions_sport_id")),
    )
    op.create_table(
        "sport_periods",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("sport_id", sa.SmallInteger(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
            name=op.f("fk_sport_periods_sport_id_sports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sport_periods")),
        sa.UniqueConstraint(
            "sport_id", "slug", name=op.f("uq_sport_periods_sport_id")
        ),
    )
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sport_id", sa.SmallInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("short_name", sa.Text(), nullable=True),
        sa.Column("abbreviation", sa.Text(), nullable=True),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("country", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_teams_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("sport_id", "slug", name=op.f("uq_teams_sport_id")),
    )
    op.create_table(
        "betting_markets",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("sport_id", sa.SmallInteger(), nullable=False),
        sa.Column("period_id", sa.SmallInteger(), nullable=True),
        sa.Column("market_type", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("has_line", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "market_type IN ('moneyline', 'spreads', 'totals', 'btts', 'draw_no_bet')",
            name="ck_betting_markets_market_type",
        ),
        sa.ForeignKeyConstraint(
            ["period_id"],
            ["sport_periods.id"],
            name=op.f("fk_betting_markets_period_id_sport_periods"),
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"],
            ["sports.id"],
            name=op.f("fk_betting_markets_sport_id_sports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_betting_markets")),
        sa.UniqueConstraint("slug", name=op.f("uq_betting_markets_slug")),
    )
    op.create_table(
        "bookmaker_competitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_bookmaker_competitions_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_bookmaker_competitions_competition_id_competitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmaker_competitions")),
        sa.UniqueConstraint(
            "bookmaker_id",
            "external_id",
            name=op.f("uq_bookmaker_competitions_bookmaker_id"),
        ),
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("job_name", sa.Text(), nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=True),
        sa.Column("competition_id", sa.Integer(), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("rows_fetched", sa.Integer(), nullable=True),
        sa.Column("rows_upserted", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_ingest_runs_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_ingest_runs_competition_id_competitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(
        "ix_ingest_runs_job_started", "ingest_runs", ["job_name", "started_at"], unique=False
    )
    op.create_table(
        "reference_competitions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.SmallInteger(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=True),
        sa.Column("external_short_name", sa.Text(), nullable=True),
        sa.Column("external_abbr", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_reference_competitions_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["reference_sources.id"],
            name=op.f("fk_reference_competitions_source_id_reference_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_competitions")),
        sa.UniqueConstraint(
            "source_id",
            "external_id",
            name=op.f("uq_reference_competitions_source_id"),
        ),
    )
    op.create_table(
        "reference_teams",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.SmallInteger(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=True),
        sa.Column("external_short_name", sa.Text(), nullable=True),
        sa.Column("external_abbr", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["reference_sources.id"],
            name=op.f("fk_reference_teams_source_id_reference_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_reference_teams_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_teams")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_reference_teams_source_id")
        ),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_seasons_competition_id_competitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
        sa.UniqueConstraint(
            "competition_id", "name", name=op.f("uq_seasons_competition_id")
        ),
    )
    op.create_table(
        "team_aliases",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=True),
        sa.Column("alias_raw", sa.Text(), nullable=False),
        sa.Column(
            "alias_norm",
            sa.Text(),
            sa.Computed(
                "lower(regexp_replace(alias_raw, '[^[:alnum:]]', '', 'g'))",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_team_aliases_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_aliases_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_aliases")),
        sa.UniqueConstraint(
            "bookmaker_id", "alias_norm", name=op.f("uq_team_aliases_bookmaker_id")
        ),
    )
    op.create_index(
        "ix_team_aliases_alias_norm", "team_aliases", ["alias_norm"], unique=False
    )
    op.create_index(
        "ix_team_aliases_alias_raw_trgm",
        "team_aliases",
        ["alias_raw"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"alias_raw": "gin_trgm_ops"},
    )
    op.create_table(
        "bookmaker_markets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("market_id", sa.SmallInteger(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_bookmaker_markets_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["betting_markets.id"],
            name=op.f("fk_bookmaker_markets_market_id_betting_markets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmaker_markets")),
        sa.UniqueConstraint(
            "bookmaker_id",
            "external_name",
            name=op.f("uq_bookmaker_markets_bookmaker_id"),
        ),
    )
    op.create_table(
        "fixtures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("sport_id", sa.SmallInteger(), nullable=False),
        sa.Column("competition_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("home_team_id", sa.Integer(), nullable=False),
        sa.Column("away_team_id", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "live",
                "finished",
                "postponed",
                "cancelled",
                "abandoned",
                name="fixture_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["away_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_away_team_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["competition_id"],
            ["competitions.id"],
            name=op.f("fk_fixtures_competition_id_competitions"),
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"],
            ["teams.id"],
            name=op.f("fk_fixtures_home_team_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_fixtures_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["sport_id"], ["sports.id"], name=op.f("fk_fixtures_sport_id_sports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fixtures")),
    )
    op.create_index("ix_fixtures_sport_id", "fixtures", ["sport_id"], unique=False)
    op.create_index(
        "ix_fixtures_competition_id_starts_at",
        "fixtures",
        ["competition_id", "starts_at"],
        unique=False,
    )
    op.create_index("ix_fixtures_season_id", "fixtures", ["season_id"], unique=False)
    op.create_index("ix_fixtures_status", "fixtures", ["status"], unique=False)
    op.create_table(
        "market_outcomes",
        sa.Column("id", sa.SmallInteger(), autoincrement=True, nullable=False),
        sa.Column("market_id", sa.SmallInteger(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["betting_markets.id"],
            name=op.f("fk_market_outcomes_market_id_betting_markets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_outcomes")),
        sa.UniqueConstraint(
            "market_id", "slug", name=op.f("uq_market_outcomes_market_id")
        ),
    )
    op.create_table(
        "reference_seasons",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.SmallInteger(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_reference_seasons_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["reference_sources.id"],
            name=op.f("fk_reference_seasons_source_id_reference_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_seasons")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_reference_seasons_source_id")
        ),
    )
    op.create_table(
        "arbitrage_opportunities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.SmallInteger(), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column("edge", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.Column(
            "total_implied_prob", sa.Numeric(precision=8, scale=6), nullable=False
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_arbitrage_opportunities_fixture_id_fixtures"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["betting_markets.id"],
            name=op.f("fk_arbitrage_opportunities_market_id_betting_markets"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arbitrage_opportunities")),
    )
    # Partial unique index — prevents duplicate active opportunities per (fixture, market, line).
    # NULLS NOT DISTINCT requires PG 15+.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_arbitrage_opportunities_active
            ON arbitrage_opportunities (fixture_id, market_id, line)
            NULLS NOT DISTINCT
            WHERE is_active = TRUE
        """
    )
    op.create_table(
        "bookmaker_fixtures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("bookmaker_competition_id", sa.Integer(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=True),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_name", sa.Text(), nullable=True),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_competition_id"],
            ["bookmaker_competitions.id"],
            name=op.f(
                "fk_bookmaker_fixtures_bookmaker_competition_id_bookmaker_competitions"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_bookmaker_fixtures_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_bookmaker_fixtures_fixture_id_fixtures"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bookmaker_fixtures")),
        sa.UniqueConstraint(
            "bookmaker_id",
            "external_id",
            name=op.f("uq_bookmaker_fixtures_bookmaker_id"),
        ),
    )
    op.create_index(
        "ix_bookmaker_fixtures_last_seen_at",
        "bookmaker_fixtures",
        ["last_seen_at"],
        unique=False,
    )
    op.create_index(
        "ix_bookmaker_fixtures_resolved",
        "bookmaker_fixtures",
        ["fixture_id"],
        unique=False,
        postgresql_where="fixture_id IS NOT NULL",
    )
    op.create_index(
        "ix_bookmaker_fixtures_unresolved",
        "bookmaker_fixtures",
        ["bookmaker_id", "bookmaker_competition_id"],
        unique=False,
        postgresql_where="fixture_id IS NULL",
    )
    op.create_table(
        "reference_fixtures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.SmallInteger(), nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("external_status", sa.Text(), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_reference_fixtures_fixture_id_fixtures"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["reference_sources.id"],
            name=op.f("fk_reference_fixtures_source_id_reference_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reference_fixtures")),
        sa.UniqueConstraint(
            "source_id", "external_id", name=op.f("uq_reference_fixtures_source_id")
        ),
    )
    op.create_table(
        "arbitrage_legs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("opportunity_id", sa.BigInteger(), nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("outcome_id", sa.SmallInteger(), nullable=False),
        sa.Column("decimal_odds", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column(
            "stake_fraction", sa.Numeric(precision=10, scale=8), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_arbitrage_legs_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["arbitrage_opportunities.id"],
            name=op.f("fk_arbitrage_legs_opportunity_id_arbitrage_opportunities"),
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name=op.f("fk_arbitrage_legs_outcome_id_market_outcomes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_arbitrage_legs")),
    )
    op.create_table(
        "odds_current",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("fixture_id", sa.Integer(), nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("bookmaker_fixture_id", sa.Integer(), nullable=False),
        sa.Column("market_id", sa.SmallInteger(), nullable=False),
        sa.Column("outcome_id", sa.SmallInteger(), nullable=False),
        sa.Column("line", sa.Numeric(precision=8, scale=2), nullable=True),
        sa.Column(
            "line_pair",
            sa.Numeric(precision=8, scale=2),
            sa.Computed("abs(line)", persisted=True),
            nullable=True,
        ),
        sa.Column("decimal_odds", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("is_available", sa.Boolean(), nullable=False),
        sa.Column(
            "observed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_fixture_id"],
            ["bookmaker_fixtures.id"],
            name=op.f("fk_odds_current_bookmaker_fixture_id_bookmaker_fixtures"),
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_odds_current_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["fixture_id"],
            ["fixtures.id"],
            name=op.f("fk_odds_current_fixture_id_fixtures"),
        ),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["betting_markets.id"],
            name=op.f("fk_odds_current_market_id_betting_markets"),
        ),
        sa.ForeignKeyConstraint(
            ["outcome_id"],
            ["market_outcomes.id"],
            name=op.f("fk_odds_current_outcome_id_market_outcomes"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_odds_current")),
    )
    op.create_index(
        "ix_odds_current_bookmaker_fixture",
        "odds_current",
        ["bookmaker_id", "fixture_id"],
        unique=False,
    )
    op.create_index(
        "ix_odds_current_fixture_available",
        "odds_current",
        ["fixture_id"],
        unique=False,
        postgresql_where="is_available = TRUE",
    )
    # Unique upsert key with nullable line — NULLS NOT DISTINCT requires PG 15+.
    op.execute(
        """
        CREATE UNIQUE INDEX uq_odds_current_key
            ON odds_current (bookmaker_fixture_id, market_id, outcome_id, line)
            NULLS NOT DISTINCT
        """
    )
    op.create_table(
        "team_alias_candidates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("bookmaker_id", sa.SmallInteger(), nullable=False),
        sa.Column("bookmaker_fixture_id", sa.Integer(), nullable=False),
        sa.Column("raw_name", sa.Text(), nullable=False),
        sa.Column("matched_team_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.Column("observation_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("promoted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_score", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.ForeignKeyConstraint(
            ["bookmaker_fixture_id"],
            ["bookmaker_fixtures.id"],
            name=op.f(
                "fk_team_alias_candidates_bookmaker_fixture_id_bookmaker_fixtures"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["bookmaker_id"],
            ["bookmakers.id"],
            name=op.f("fk_team_alias_candidates_bookmaker_id_bookmakers"),
        ),
        sa.ForeignKeyConstraint(
            ["matched_team_id"],
            ["teams.id"],
            name=op.f("fk_team_alias_candidates_matched_team_id_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_team_alias_candidates")),
        sa.UniqueConstraint(
            "bookmaker_id",
            "raw_name",
            "matched_team_id",
            name=op.f("uq_team_alias_candidates_bookmaker_id"),
        ),
    )
    op.create_index(
        "ix_team_alias_candidates_score",
        "team_alias_candidates",
        ["bookmaker_id", "score"],
        unique=False,
        postgresql_where="promoted_at IS NULL",
    )
    # odds_history: range-partitioned table — cannot be autogenerated by Alembic.
    for stmt in _odds_history_statements():
        op.execute(sa.text(stmt))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS odds_history CASCADE")
    op.drop_index(
        "ix_team_alias_candidates_score",
        table_name="team_alias_candidates",
        postgresql_where="promoted_at IS NULL",
    )
    op.drop_table("team_alias_candidates")
    op.execute("DROP INDEX IF EXISTS uq_odds_current_key")
    op.drop_index(
        "ix_odds_current_fixture_available",
        table_name="odds_current",
        postgresql_where="is_available = TRUE",
    )
    op.drop_index("ix_odds_current_bookmaker_fixture", table_name="odds_current")
    op.drop_table("odds_current")
    op.drop_table("arbitrage_legs")
    op.drop_table("reference_fixtures")
    op.drop_index(
        "ix_bookmaker_fixtures_unresolved",
        table_name="bookmaker_fixtures",
        postgresql_where="fixture_id IS NULL",
    )
    op.drop_index(
        "ix_bookmaker_fixtures_resolved",
        table_name="bookmaker_fixtures",
        postgresql_where="fixture_id IS NOT NULL",
    )
    op.drop_index(
        "ix_bookmaker_fixtures_last_seen_at", table_name="bookmaker_fixtures"
    )
    op.drop_table("bookmaker_fixtures")
    op.execute("DROP INDEX IF EXISTS uq_arbitrage_opportunities_active")
    op.drop_table("arbitrage_opportunities")
    op.drop_table("reference_seasons")
    op.drop_table("market_outcomes")
    op.drop_index("ix_fixtures_status", table_name="fixtures")
    op.drop_index("ix_fixtures_season_id", table_name="fixtures")
    op.drop_index("ix_fixtures_competition_id_starts_at", table_name="fixtures")
    op.drop_index("ix_fixtures_sport_id", table_name="fixtures")
    op.drop_table("fixtures")
    op.execute("DROP TYPE IF EXISTS fixture_status")
    op.drop_table("bookmaker_markets")
    op.drop_index(
        "ix_team_aliases_alias_raw_trgm",
        table_name="team_aliases",
        postgresql_using="gin",
        postgresql_ops={"alias_raw": "gin_trgm_ops"},
    )
    op.drop_index("ix_team_aliases_alias_norm", table_name="team_aliases")
    op.drop_table("team_aliases")
    op.drop_table("seasons")
    op.drop_table("reference_teams")
    op.drop_table("reference_competitions")
    op.drop_index("ix_ingest_runs_job_started", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_table("bookmaker_competitions")
    op.drop_table("betting_markets")
    op.drop_table("teams")
    op.drop_table("sport_periods")
    op.drop_table("competitions")
    op.drop_table("sports")
    op.drop_table("reference_sources")
    op.drop_table("bookmakers")
    # ### end Alembic commands ###
